config/routes.rb
JustMovieManager::Application.routes.draw do

  resources :movies
  root :to => "movies#index"

  resources :akas_imdbs do
    collection do
      get 'add_movie'
      post 'import_movies'
    end
  end
  
  mount Resque::Server, :at => "/resque"

end

app/models/akas_imdb.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.

class AkasImdb
  def self.imdb_raw(title)
    Imdb::Search.new(title)
  end

  def self.new(id)
    Imdb::Movie.new(id)
  end

  def self.suggest_list(title)
   Imdb::Search.new(title).movies[0..5]
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  after_destroy :remove_poster

  def self.fetch_movies(args)
    if args[:search].present?
      where('title ILIKE ?', "%#{args[:search]}%").paginate(:page => args[:page], :per_page => 14)
    else
      #Movie.find(:all,:order => sort_column(args[:sort]) + " " + sort_order(args[:direction]) )
      order(sort_column(args[:sort]) + " " + sort_order(args[:direction])).paginate(:page => args[:page], :per_page => 14)
    end
  end
  
  private

  def remove_poster
    path = "#{Rails.root}/app/assets/images/posters/#{self.imdb_id}_small.jpg"
    File.delete(path) if File.exist?(path)
    File.delete(path) if File.exist?(path)
  end
  
  def self.sort_column(column)
    Movie.column_names.include?(column) ? column : "created_at"
  end

  def self.sort_order(direction)
    %w[asc desc].include?(direction) ? direction : "desc"
  end
  
end

app/models/redis_data.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.

class RedisData
  def self.redis_con
    @@limit = 14
    @@redis= Redis.new()    
  end

  def self.get_rescent_views(remote_ip)
    key = "remote_ip:" + remote_ip
    trigger = @@redis.HGET(key ,"trigger")
    a = []
    if trigger != nil
      if @@redis.HLEN( key).length > 1
        @@limit.times{
          a << @@redis.HGET( key ,trigger )
          trigger =  trigger == @@limit ? 1 : trigger + 1
        }
      end
    else
      # Just to keep the number of users visited the site even if not browsed
      @@redis.HSETkey( key, "trigger", 0 )
    end


  end
  
end

app/controllers/akas_imdbs_controller.rb
class AkasImdbsController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    if params[:movie_title].present?
      search =  AkasImdb.imdb_raw(params[:movie_title])
      @fetched_movies =  search.movies[0..3]      
    end
    
    if params[:dir_path].present?    
      @dir_files = fetch_names_from_folder(params[:dir_path])      
    end

  end

  def add_movie   
    Resque.enqueue(FetchMovie,params[:imdb_id] )
    #FetchMovie.perform params[:imdb_id]
    redirect_to movies_path
  end

  def import_movies
    Resque.enqueue(FetchMovie,nil,params[:movies] )
    redirect_to movies_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def fetch_names_from_folder(path = "media/New Volume/Movies/*")
    files = Dir.entries(path)
    files.delete_if {|x| x == '.' || x == '..' || x.include?('.srt') || x.include?('sub') || x.include?('.db')}
    Movie.all.each do |movie|       
       files.delete_if {|x| movie.title == x }
    end
    files
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  #before_filter :load_redis
  http_basic_authenticate_with :name => "just", :password => "bazinga", :except => [:index , :show]
  
  def index
    #@movies = Movie.search(params[:search])
    #@movies = Movie.order(sort_column + " " + sort_order)
    @movies = Movie.fetch_movies(params)
    #@rescent_views =  RedisData.get_rescent_views(request.remote_ip.to_s)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

  end
  
  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])
    @fetched_movies =  AkasImdb.suggest_list(params[:movie][:title]) if params[:imdb_id] == nil && params[:movie][:title] && params[:movie][:imdb_id].blank?

    respond_to do |format|
      if params[:imdb_id] || @fetched_movies.try(:length) == 1
        begin
          Resque.enqueue(FetchMovie,params[:imdb_id] || @fetched_movies.first.id)
        rescue
          FetchMovie.perform(params[:imdb_id] || @fetched_movies.first.id)
        end
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
        format.xhr( render :nothing => true)
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end

  private
  def load_redis
    @redis = RedisData.redis_con
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def sortable(column ,title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    direction = direction == "asc" ? "desc" : "asc" if %w[created_at imdb_rating my_rating year].include?(column) unless column == params[:sort]
    link_to title , :sort => column ,:direction => direction
  end
  
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/akas_imdbs/_dir_results_fetched.html.erb
  <h3>Your HDD movies</h3>
  <%= form_tag import_movies_akas_imdbs_path do  %>
    <% files.each do |file| %>
      <%= check_box_tag "movies[]", file %>
      <%= file %>
      <br/>
    <% end %>

    <div class="actions">
      <%= submit_tag "Add Movies" %>
    </div>
  <% end %>

app/views/akas_imdbs/_form.html.erb
<%= form_tag akas_imdbs_path , :multipart => true ,:method => :get do |f| %>
  <div class="field">
    <%= label_tag :movie_title %><br />
    <%= text_field_tag :movie_title %>
  </div>
  <div class="field">
    <%= label_tag :imdb_id %><br />
    <%= text_field_tag :imdb_id %>
  </div>
  <div class="field">
    <%= label_tag :url %><br />
    <%= text_field_tag :url %>
  </div>

  <h2>Or specify Path here</h2>
  <div class="field">
    <%= label_tag :directory_path %><br />
    <%= text_field_tag :dir_path %>
  </div>
  <div class="field">
    <%= label_tag :browse_file %><br />
    <%= file_field_tag :file_path %>
  </div>

  <div class="actions">
    <%= submit_tag "Search" %>
  </div>
<% end %>

app/views/akas_imdbs/_search_results.html.erb
<% if movies %>
<h3> Click the  movie for saving </h3>
  <% movies.each do |movie| %>
    <%= link_to movie.title ,:controller => 'akas_imdbs',:action => 'add_movie' ,:imdb_id => movie.id %>
    <br/>
    <br/>
  <% end %>
<% end %>

app/views/akas_imdbs/index.html.erb
<h2>Import some movies now</h2>
<%= render 'form' %>

<br/>
<% if @dir_files %>
<%= render 'dir_results_fetched' ,:files => @dir_files %>
<% end %>

<%= render 'search_results', :movies => @fetched_movies %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JusT's Movie Manager</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body data-spy="scroll" data-target=".subnav" data-offset="50">
    <div class="topbar">
      <div class="fill">
        <div class="container">
            <%= link_to "Movie Manager",movies_path ,:class => "brand" %>
          <ul class="nav">
            <li class="active"><%= link_to "Home",movies_path %></li>
            <li><a href="#about">About</a></li>
            <li><%= link_to "Add Movies", new_movie_path %></li>
          </ul>          
          <%= form_tag movies_path ,:method => :get, :html => {:class => "pull-left"} do %>
            <%= text_field_tag :search ,params[:search] ,:placeholder => "Search Movie" %>
            <%= submit_tag :search %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <%#*<div class="sidebar">%>
        <%#*<div class="well">%>
        <%#*</div>%>
      <%#*</div>%>
      <div class="container">
        <%= yield %>
      </div>
      <%#*<footer>%>
        <%#*<p>&copy; Company 2012</p>%>
      <%#*</footer>%>
    </div>


  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => {:class => "add_movie_form"}) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @fetched_movies != nil %>
    <h3> Click the button for saving </h3>
    <% @fetched_movies.each do |movie| %>
      <%= submit_tag  'Add Movie', :name => 'save' ,:id => 'submit_movie',:class => "btn" ,:onclick => "set_imdb_id('#{movie.id.to_s}')",:imdb_id => movie.id %><%= link_to movie.title, '#',  :class => 'movie_fetched' ,:id => movie.id %>
      <br/>
      <br/>
    <% end %>
    <%= hidden_field_tag :imdb_id %>
  <% else %>

    <div class="clearfix">
      <%= f.label :title %>
      <div class="input">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="clearfix">
      <%= f.label :imdb_id%>
      <div class="input">
        <%= f.text_field :imdb_id %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<%= sortable "title" %>
<%= sortable "year" %>
<%= sortable "created_at","Date Added" %>
<%= sortable "imdb_rating" %>
<%= sortable "my_rating" %>
<br />

<div class="hero-unit">
  <ul id="nav">
    <% @movies.each do |movie| %>
      <% if movie.director %>
        <li>
          <div class="movie-block-index">
            <%#= link_to image_tag("posters/#{movie.imdb_id}_small.jpg" , :border => 0 ,:width => 135, :height => 200) , movie ,{:id => "a-block", :class=>"image-hover-over" }%>
            <% if movie.poster_1 %>
                  <%= link_to image_tag(movie.poster_1 , :border => 0 ,:width => 135, :height => 200) , movie ,{:id => "a-block", :class=>"image-hover-over" }%>
                <% else %>
                  <%= link_to image_tag("posters/#{movie.imdb_id}_small.jpg" , :border => 0 ,:width => 135, :height => 200) , movie ,{:id => "a-block", :class=>"image-hover-over" }%>
                <% end %>
       <!--<img src=<%=movie.poster_1 %> width="135"  height="200" border="0" alt="awesome" />-->
          </div>
          <%= link_to truncate(movie.title, :length => 22, :omission => '...') ,movie ,params.merge(:sort => params[:sort])%>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>
<%= will_paginate @movies, :inner_window => 2, :outer_window => 2 %>

app/views/movies/new.html.erb
<h3>New Movie</h3>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div id="movie-show" class="title-overview">
  <table id="title-overview-widget-layout">
    <tbody>
      <tr>
        <td rowspan="2" >
          <div id="image_primary">
            <%= image_tag "posters/#{@movie.imdb_id}_small.jpg" %>
            <%#= image_tag(@movie.poster_2) %>
          </div>
        </td>
        <td id="movie-details">
          <div class="page-header-movie">
            <h2><%=link_to @movie.title , @movie.url %></h2>
            <small><%= @movie.length %> mins - <%= @movie.genres %><br/> - <%= @movie.release_date %></small>
          </div>
          <div class="star-box">
            <div class="imdb-ratings">
              <div class="star-box-giga-star">
                <%= @movie.imdb_rating %>
              </div>
              <span>Imdb Ratings</span>
            </div>

            <div class="my-ratings">
              <% form_id = "movie_#{@movie.id}_rating" %>
              <%= form_for @movie, :html => {:id => "movie_#{@movie.id}_rating" } do |f| %>
                <%= f.hidden_field  :my_rating %>
                <% (1..10).each do |i| %>
                  <li class="rating-star <%= 'on' if @movie.my_rating >= i %>"style="list-style:none" data-stars="<%= i %>" id =<%= "#{form_id}_#{i}"%> data-form-id=<%= "#{form_id}"%>></li>
                <%end%>
                <span class="rating-helper"><%=@movie.my_rating.try(:to_i)%>/10</span>
              <%end%>
            </div>
          </div>
          <p><%= @movie.plot %> </p>
          <p></p>
          <div class="text-block">
            <h4 class="inline">Director:</h4> <%= @movie.director %>
          </div>
          <div class="text-block">
            <h4 class="inline">Stars:</h4> <%= @movie.cast_members.split(',')[0..5].join(",") %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_movie_path(@movie) ,{:class=> 'btn primary'}%>
<%= link_to 'Back', movies_path,{:class=> 'btn primary'}%>
<%= link_to 'Destroy', @movie, :confirm => 'Are you sure?', :method => :delete ,:class=> 'btn primary' %>